---
name: "tagged-release"

on:
  push:
    tags:
      - "v*"

jobs:
  tagged-release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"
    permissions:
      contents: write

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Package release"
        run: ./pack-extension.sh

      - name: "Release"
        uses: ncipollo/release-action@v1
        with:
          artifacts: "extension.zip,LICENSE.txt"
          generateReleaseNotes: true

